/*DATAMIGRATION 880F7FF2-E0F6-4F04-AEC0-C435FB235CCC*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'LightDMS', 'FileContent';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'FileContent', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'FileContent', 'CreatedDate', 'datetime2';
GO

UPDATE _LightDMS.FileContent
SET CreatedDate = GETDATE()
WHERE CreatedDate IS NULL

EXEC Rhetos.DataMigrationApplyMultiple 'LightDMS', 'FileContent', 'ID, CreatedDate';