/*DATAMIGRATION CE0FC816-A00F-4640-ABE3-7138B49A7815*/ -- Change the script's code only if the it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'LightDMS', 'DocumentRepository';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'DocumentRepository', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'DocumentRepository', 'RepositoryName', 'nvarchar(MAX)';
GO

IF NOT EXISTS(SELECT TOP 1 NULL FROM _LightDMS.DocumentRepository where ID = 'CE0FC816-A00F-4640-ABE3-7138B49A7815')
INSERT INTO _LightDMS.DocumentRepository (ID, RepositoryName) VALUES ('CE0FC816-A00F-4640-ABE3-7138B49A7815', 'DefaultRepository')

EXEC Rhetos.DataMigrationApplyMultiple 'LightDMS', 'DocumentRepository', 'ID, RepositoryName';