/*DATAMIGRATION 9ADC0B53-3E8B-48C0-9AE1-39A7E50CB363*/ -- Change the script's code only if the it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'LightDMS', 'Checkout';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'DocumentVersion', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'DocumentVersion', 'ExternalEntityID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'DocumentVersion', 'DocumentID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'LightDMS', 'Checkout', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'Checkout', 'ExternalEntityID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'Checkout', 'DocumentID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'LightDMS', 'UndoCheckout', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'UndoCheckout', 'ExternalEntityID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'LightDMS', 'UndoCheckout', 'DocumentID', 'uniqueidentifier';

GO

UPDATE _LightDMS.DocumentVersion SET DocumentID = ExternalEntityID WHERE DocumentID IS NULL AND ExternalEntityID IS NOT NULL;
UPDATE _LightDMS.Checkout SET DocumentID = ExternalEntityID WHERE DocumentID IS NULL AND ExternalEntityID IS NOT NULL;
UPDATE _LightDMS.UndoCheckout SET DocumentID = ExternalEntityID WHERE DocumentID IS NULL AND ExternalEntityID IS NOT NULL;

EXEC Rhetos.DataMigrationApplyMultiple 'LightDMS', 'DocumentVersion', 'ID, DocumentID';
EXEC Rhetos.DataMigrationApplyMultiple 'LightDMS', 'Checkout', 'ID, DocumentID';
EXEC Rhetos.DataMigrationApplyMultiple 'LightDMS', 'UndoCheckout', 'ID, DocumentID';
