/*DATAMIGRATION 9A2A9B64-A2BF-4F70-B507-CA887E4290B9*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Rhetos', 'AppliedConcept';
EXEC Rhetos.DataMigrationUse 'Rhetos', 'AppliedConcept', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Rhetos', 'AppliedConcept', 'RemoveQuery', 'nvarchar(MAX)';
EXEC Rhetos.DataMigrationUse 'Rhetos', 'AppliedConcept', 'ConceptInfoKey', 'nvarchar(MAX)';
GO

UPDATE _Rhetos.AppliedConcept SET RemoveQuery = '-- Zbog performansi ne uklanjamo filestream. Potrebno je ručno napraviti ako se radi downgrade servera' 
WHERE ConceptInfoKey = 'SqlObjectInfo LightDMS.FileContent_FileStream'

EXEC Rhetos.DataMigrationApplyMultiple 'Rhetos', 'AppliedConcept', 'ID, RemoveQuery';